add_bos_token: false
add_eos_token: false
attack_data_path: attack
attack_kind: stat
block_size: 128
buffer_size: 1
cache_path: ./cache
calibration: true
ceil_pct: false
dataset_config_name: wikitext-103-raw-v1
dataset_name: wikitext
eval_batch_size: 1
eval_end_idx: 1000
eval_sta_idx: 0
half: false
int8: false
load_attack_data: false
mask_filling_model_name: t5-base
mask_top_p: 1.0
maximum_samples: 1000
model_name: gpt2
packing: true
pad_token_id: null
pct: 0.3
perturbation_number: 1
preprocessing_num_workers: 1
random_seed: 48
reference_model: ''
sample_number: 10
span_length: 2
target_model: ''
train_end_idx: 10000
train_sta_idx: 0
use_dataset_cache: true
validation_split_percentage: 0.1
